#!/usr/bin/env python3
"""Assemble an episode's engine inputs from its src/ folder.

The engine wants one visuals.mjs and one episode.spec.json. For a long film it is easier to keep the narration
and beat phrases in src/script.py, the episode's settings in src/episode.json, and each scene in
src/scenes/sNN.js + sNN.json, so scenes can be written and previewed one at a time, by several writers at once.

  build.py <episode>                         write visuals.mjs and episode.spec.json into the episode directory
  build.py <episode> --only S03,S04 --out D  write a small proof episode with just those scenes into directory D
  build.py <episode> --beats S03             print where each beat of a scene falls in the 10-second silent preview

A scene with no sNN.js yet is drawn as a placeholder and reported.
"""
import argparse
import importlib.util
import json
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "engine"))
from sfx import SOUNDS  # noqa: E402
from spec import narration_blocks  # noqa: E402

HEADER = """// Generated by tools/build.py from src/scenes; edit the scene files and rebuild rather than editing this file.
// Every scene is a place where something happens, drawn as a pure function of time. The characters, camera,
// transitions and props come from kit.mjs.
"""
PLACEHOLDER = """// ---------- {sid}: this scene has not been written yet ----------
function scene{n}(ctx, f, s, L, vis) {{
  studio(ctx, f.t); floor(ctx);
  drawBot(ctx, {{ ...botAlive(f.t, true), x: 960, y: 856, s: .9 }});
}}
"""
DISPATCH = """
// ---------- Transitions between scenes ----------
const SCENES = [{scenes}];
// How scene i hands over to scene i+1: 'band' is a colour band sweeping across, [x, y] opens a circle from that point.
const CUTS = {cuts};

export function draw(ctx, f) {{
  const i = f.scenes.indexOf(f.scene), s = f.scene, t = f.t, last = f.scenes.length - 1;
  const vis = (i === 0 ? 1 : seg(t, s.start + .3, .25)) * (i === last ? 1 : 1 - seg(t, s.end - .4, .25));
  const paint = (index, alpha) => {{ ctx.save(); SCENES[index](ctx, f, f.scenes[index], t - f.scenes[index].start, alpha); ctx.restore(); }};
  const from = i > 0 ? CUTS[i - 1] : null;
  const open = Array.isArray(from) ? seg(t, s.start, .6) : 1;
  if (open < 1) {{ paint(i - 1, 0); iris(ctx, open, from[0], from[1], () => paint(i, vis)); }}
  else paint(i, vis);
  if (from === 'band') wipe(ctx, .5 + seg(t, s.start, .32) * .5);
  if (i < last && CUTS[i] === 'band') wipe(ctx, seg(t, s.end - .32, .32) * .5);
}}
"""


def fail(message):
    sys.exit(f"build.py: {message}")


def load_script(episode):
    """src/script.py holds SCENES = [(id, narration, {beat key: phrase}), ...] and a check() that validates them."""
    path = episode / "src" / "script.py"
    if not path.is_file():
        fail(f"{path} is missing")
    spec = importlib.util.spec_from_file_location("episode_script", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.check()
    return module


def load_scene(episode, sid):
    n = sid[1:]
    code, meta = episode / "src" / "scenes" / f"s{n}.js", episode / "src" / "scenes" / f"s{n}.json"
    if not code.is_file():
        return PLACEHOLDER.format(sid=sid, n=n), {"labels": {}, "sfx": {}, "cut": "band"}, False
    if not meta.is_file():
        fail(f"{code.name} has no {meta.name}")
    source, data = code.read_text(encoding="utf-8"), json.loads(meta.read_text(encoding="utf-8"))
    if f"function scene{n}(" not in source:
        fail(f"{code.name} must define function scene{n}(ctx, f, s, L, vis)")
    unknown = set(data) - {"labels", "sfx", "cut", "pause_after"}
    if unknown:
        fail(f"{meta.name} has unknown fields {sorted(unknown)}")
    for key in data.get("labels", {}):
        if not re.fullmatch(rf"s{n}_[a-z0-9_]+", key):
            fail(f"{meta.name}: label key {key} must start with s{n}_")
    bad = sorted(set(data.get("sfx", {}).values()) - set(SOUNDS))
    if bad:
        fail(f"{meta.name}: unknown sounds {bad}; use one of {sorted(SOUNDS)}")
    cut = data.get("cut", "band")
    if not (cut == "band" or (isinstance(cut, list) and len(cut) == 2 and all(isinstance(v, (int, float)) for v in cut))):
        fail(f"{meta.name}: cut must be \"band\" or [x, y]")
    return source.rstrip() + "\n", data, True


def build(episode, only, out):
    script = load_script(episode)
    settings_path = episode / "src" / "episode.json"
    if not settings_path.is_file():
        fail(f"{settings_path} is missing")
    settings = json.loads(settings_path.read_text(encoding="utf-8"))
    sources = settings.get("sources", [])
    table = {sid: (text, reveals) for sid, text, reveals in script.SCENES}
    chosen = only or list(table)
    for sid in chosen:
        if sid not in table:
            fail(f"unknown scene {sid}")
    proof = out.resolve() != episode.resolve()
    out.mkdir(parents=True, exist_ok=True)
    parts, labels, cuts, spec_scenes, missing = [], {}, [], [], []
    for index, sid in enumerate(chosen):
        code, data, written = load_scene(episode, sid)
        if not written:
            missing.append(sid)
        parts.append(code)
        clash = set(labels) & set(data.get("labels", {}))
        if clash:
            fail(f"duplicate label keys {sorted(clash)}")
        labels.update(data.get("labels", {}))
        cuts.append(data.get("cut", "band"))
        text, reveals = table[sid]
        last = index == len(chosen) - 1
        entry = {"id": f"S{index + 1:02}" if proof else sid,
                 "pause_after": settings.get("closing_pause", 3.0) if last and not proof else data.get("pause_after", 0.3), "reveals": reveals}
        sfx = {k: v for k, v in data.get("sfx", {}).items() if not (k == "start" and index == 0)}
        if sfx:
            entry["sfx"] = sfx
        cited = settings.get("scene_source", {}).get(sid)
        if cited and not proof:
            source = next((item for item in sources if item["id"] == cited), None) or fail(f"scene_source.{sid} names {cited}, which is not in sources")
            entry["source"] = {"ids": [source["id"]], "text": source["label"]}
        spec_scenes.append(entry)
    label_lines = ",\n".join(f"  {key}: {json.dumps(text, ensure_ascii=False)}" for key, text in labels.items())
    visuals = (HEADER + "\nexport const labels = {\n" + label_lines + ("," if label_lines else "") + "\n};\n\n" + "\n".join(parts)
               + DISPATCH.format(scenes=", ".join(f"scene{sid[1:]}" for sid in chosen), cuts=json.dumps(cuts[:-1])))
    (out / "visuals.mjs").write_text(visuals, encoding="utf-8")
    spec = {**settings["spec"], "sources": [] if proof else sources, "scenes": spec_scenes}
    (out / "episode.spec.json").write_text(json.dumps(spec, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    sheet = out / spec.get("sheet", "production-sheet.md")
    if proof:
        shutil.copyfile(episode / "kit.mjs", out / "kit.mjs")
        blocks = "".join(f"### S{i + 1:02} 旁白\n\n{table[sid][0]}\n\n" for i, sid in enumerate(chosen))
        sheet.write_text(f"# 样张制作单（{'、'.join(chosen)}）\n\n上屏数字清单：{settings.get('numbers', '')}。\n\n## 完整旁白\n\n{blocks}", encoding="utf-8")
    else:
        if not sheet.is_file():
            fail(f"{sheet.name} is missing; it holds the fact ledger and is written by hand")
        # Read the sheet the way the engine does, so a second paragraph the script does not have is caught too.
        found = dict(narration_blocks(sheet.read_text(encoding="utf-8")))
        wrong = [sid for sid in chosen if found.get(sid) != table[sid][0]]
        if wrong or len(found) != len(chosen):
            fail(f"{sheet.name} narration differs from src/script.py at {wrong or 'scene count'}")
    print(f"built {len(chosen)} scenes, {len(labels)} labels into {out}" + (f"; placeholders: {', '.join(missing)}" if missing else ""))


def beats(episode, sid):
    """Where the silent preview puts each beat: a scene lasts 10 s and a beat sits where its phrase sits in the text."""
    script = load_script(episode)
    found = [(t, r) for s, t, r in script.SCENES if s == sid]
    if not found:
        fail(f"unknown scene {sid}")
    text, reveals = found[0]
    for key, phrase in reveals.items():
        print(f"{sid} {key:10} {10 * text.index(phrase) / len(text):5.2f} s  {phrase}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("episode", type=Path)
    parser.add_argument("--only")
    parser.add_argument("--out", type=Path)
    parser.add_argument("--beats")
    args = parser.parse_args()
    if not args.episode.is_dir():
        fail(f"{args.episode} is not a directory")
    if args.beats:
        beats(args.episode, args.beats)
    else:
        build(args.episode, args.only.split(",") if args.only else None, args.out or args.episode)
